import fs from 'fs';
import path from 'path';
import { MIND_BENCHMARK_FILE, MIND_BROWSER_DIR, MIND_CACHE_DIR, MIND_HISTORY_DIR, projectRoot, SCRIPTS_DIR } from '../config';

/**
 * One-time move of the local .mind folders into .mindar/ (2026-09-28; before: mind-ar/, mind-history/,
 * scripts/.cache/). Remove once every working copy has run the build once.
 */
export function moveOldLocalFolders(): void {
  const moves: [string, string][] = [
    [path.join(projectRoot, 'mind-history'), MIND_HISTORY_DIR],
    [path.join(SCRIPTS_DIR, '.cache/mind'), MIND_CACHE_DIR],
    [path.join(SCRIPTS_DIR, '.cache/mind-browser'), MIND_BROWSER_DIR],
    [path.join(SCRIPTS_DIR, '.cache/mind-benchmark.json'), MIND_BENCHMARK_FILE],
  ];
  for (const [from, to] of moves) {
    if (!fs.existsSync(from) || fs.existsSync(to)) continue;
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.renameSync(from, to);
    console.log(`📦 Moved ${path.relative(projectRoot, from)} → ${path.relative(projectRoot, to)}`);
  }
  // Regenerated by every build – the old copy just goes
  for (const old of [path.join(projectRoot, 'mind-ar'), path.join(SCRIPTS_DIR, '.cache')]) {
    const empty = fs.existsSync(old) && (old.endsWith('mind-ar') || fs.readdirSync(old).length === 0);
    if (empty) fs.rmSync(old, { recursive: true, force: true });
  }
}
