// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "about": {
    "account": "Account",
    "android": "Android: Chrome",
    "appBy": "App by Tilman Porschuetz",
    "author": "Author: {{author}}",
    "colophon": "Colophon",
    "desktop": "Desktop: Chrome, Firefox, Safari",
    "imageTracking": "Image tracking by",
    "info": "Info",
    "infoText": "{{title}} is a publication by {{author}}. Scan the pages of the book to unlock entries – glossary terms, videos, texts and links – and read them here in consultation mode.",
    "ios": "iOS: Safari, Chrome",
    "publishedBy": "Published by buildingfictions © 2027",
    "requirements": "Requires a WebXR compatible browser and a copy of the book.",
    "settings": "Settings"
  },
  "account": {
    "artistUpdates": "Receive updates from {{author}}",
    "bookUpdates": "Receive updates on {{title}}",
    "codeLabel": "Code from the email",
    "confirm": "Confirm",
    "confirmed": "Your email address is confirmed – you're signed in.",
    "delete": "Delete account",
    "deleteConfirm": "Delete your account and everything stored in it? Your progress stays on this device.",
    "deleted": "Your account was deleted. Your progress stays on this device.",
    "emailPlaceholder": "Your email address",
    "errors": {
      "already-used": "This link or code was used already. Request a new email to sign in on this device.",
      "expired": "This link or code has expired. Request a new email.",
      "invalid-code": "This code isn't right. Check the email and try again.",
      "invalid-email": "This email address doesn't look right.",
      "invalid-link": "This link isn't valid. Request a new email.",
      "mail-failed": "The email could not be sent. Try again later.",
      "offline": "No connection to the server. Check your internet connection.",
      "server-error": "Something went wrong. Try again later.",
      "too-many-attempts": "Too many wrong codes. Request a new email.",
      "too-many-requests": "Too many emails in a short time. Try again in an hour.",
      "unauthorized": "You're signed out. Sign in again."
    },
    "optionsLabel": "Updates",
    "otherEmail": "Use another email",
    "pendingDescription": "We sent an email to {{email}}. Open the link in it, or enter the code here:",
    "publisherUpdates": "Receive updates from Building Fictions",
    "send": "Register account",
    "sendAgain": "Send again",
    "signOut": "Sign out",
    "signedInAs": "Signed in as",
    "signedOut": "You're signed out. Your progress stays on this device.",
    "signedOutDescription": "Register your copy now to save your progress and receive updates in your inbox.",
    "syncPending": "Your progress will be saved in your account when you're online again.",
    "syncSynced": "Your progress is saved in your account.",
    "syncSyncing": "Saving your progress in your account …"
  },
  "camera": {
    "allow": "Please allow the camera to scan the book.",
    "continueWithout": "Continue without camera",
    "denied": "Camera access was denied.",
    "enable": "Allow the camera for this site in your browser settings, then reload the page.",
    "illustration": "Camera",
    "notResponding": "The camera is not responding.",
    "notRespondingHelp": "Reload the page. If that doesn't help, close your browser completely and open it again – another app may still be using the camera.",
    "reload": "Reload page",
    "unavailable": "The camera only works over a secure connection. Open the app with https:// and try again.",
    "waiting": "Waiting for camera access…"
  },
  "common": {
    "dismiss": "Dismiss",
    "goToStart": "Go to start",
    "loading": "Loading",
    "loadingBook": "Loading book",
    "markAlt": "Mark the Page"
  },
  "entries": {
    "categories": {
      "glossary": "Glossary",
      "link": "Links",
      "text": "Texts",
      "video": "Videos"
    },
    "countAria": "{{consulted}} of {{total}} consulted",
    "empty": "No entries consulted yet.",
    "locked": "locked"
  },
  "entry": {
    "accessPage": "Access page",
    "author": "Author",
    "category": "Category",
    "entryName": "Entry name",
    "goToPage": "Go to access page {{page}} in scan mode to see the video.",
    "missing": "This entry is not part of the book (anymore).",
    "openInNewTab": "Open in a new tab",
    "preview": "Preview (the AR version is shown on the page):"
  },
  "header": {
    "backToScan": "Back to scan mode",
    "counterAria": "{{consulted}} of {{total}} entries consulted",
    "entries": "Entries",
    "entriesConsulted": "Entries consulted",
    "info": "Info",
    "openConsultation": "Open consultation mode"
  },
  "notFound": {
    "text": "This page doesn't exist (anymore)."
  },
  "progress": {
    "converted": "Your saved progress was converted for this app version. Parts of it may be missing.",
    "reset": "Your saved progress could not be read by this app version and was reset."
  },
  "scan": {
    "newEntryUnlocked": "New entry unlocked",
    "openEntry": "Open entry {{title}}",
    "pagesActivated": "Pages activated:",
    "pagesAria": "Pages {{pages}}"
  },
  "settings": {
    "downloadButton": "Download all content",
    "downloadDescription": "Loads all content of the book ({{size}}) onto this device in advance, so nothing has to load while you use the app – faster, and it also works without internet. Best on Wi-Fi.",
    "downloadDone": "All content is on this device ({{size}}) – nothing has to load while you use the app.",
    "downloadFailed": "Some files could not be downloaded ({{size}} in total). Check your connection and try again.",
    "downloadProgress": "{{loaded}} of {{total}} downloaded",
    "downloadStored": "{{loaded}} of {{total}} on this device",
    "feedbackDescription": "Short sounds and vibrations when you scroll through the pages, tap a button or find a page.",
    "hapticsLabel": "Vibration",
    "historyButton": "Reset progress",
    "historyConfirm": "Delete all saved progress for this book on this device?",
    "historyConfirmAccount": "Delete all saved progress for this book – on this device and in your account?",
    "historyDescription": "The app keeps track of all the entries you have found and explored in the book. If you like, you can delete your progress and start over – or save it to your account below.",
    "historyDescriptionAccount": "The app keeps track of all the entries you have found and explored in the book – on this device and in your account. Resetting deletes your progress in both places, so you can start over.",
    "historyDescriptionLocal": "The app keeps track of all the entries you have found and explored in the book. If you like, you can delete your progress and start over.",
    "historyDone": "All saved progress on this device was deleted.",
    "installAdded": "The app is installed – open it from your home screen or app list.",
    "installButton": "Install as app on this device",
    "installDescription": "The app then opens full screen from its own icon and starts faster.",
    "installDone": "You're using the app from your home screen.",
    "installIos": "In Safari, tap Share (the square with the arrow), then \"Add to Home Screen\". The app then opens full screen from its own icon.",
    "installManual": "Open your browser's menu and choose \"Add to Home Screen\" or \"Install app\", if your browser offers it.",
    "languageChange": "Change language",
    "languageLabel": "Language:",
    "soundLabel": "Sounds"
  },
  "startup": {
    "contentNotLoaded": "The book content could not be loaded.",
    "contentOtherVersion": "The book content was built for another app version.",
    "unknownError": "An unknown error occurred."
  },
  "tutorial": {
    "skip": "Skip"
  }
}
