// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "about": {
    "android": "Android: Chrome",
    "appBy": "App by Tilman Porschuetz",
    "author": "Author: {{author}}",
    "colophon": "Colophon",
    "desktop": "Desktop: Chrome, Firefox, Safari",
    "info": "Info",
    "infoText": "{{title}} is a publication by {{author}}. Scan the pages of the book to unlock entries – glossary terms, videos, texts and links – and read them here in consultation mode.",
    "ios": "iOS: Safari, Chrome",
    "publishedBy": "Published by buildingfictions © 2025",
    "requirements": "Requires a WebXR compatible browser and a copy of the book.",
    "settings": "Settings"
  },
  "camera": {
    "allow": "Please allow the camera to scan the book.",
    "chromeSteps": {
      "0": "Tap the lock / settings icon in the address bar",
      "1": "Select \"Site settings\"",
      "2": "Allow camera permissions",
      "3": "Refresh the page"
    },
    "chromeTitle": "To enable camera access in Chrome:",
    "continueWithout": "Continue without camera",
    "denied": "Camera access was denied.",
    "enable": "To scan the book and display interactive content, please enable camera permissions in your browser settings.",
    "firefoxSteps": {
      "0": "Tap the lock icon in the address bar",
      "1": "Clear the current setting",
      "2": "Refresh the page and allow access when prompted"
    },
    "firefoxTitle": "To enable camera access in Firefox:",
    "illustration": "Camera",
    "otherSteps": {
      "0": "Check your browser settings for camera permissions",
      "1": "Allow this site to use your camera",
      "2": "Refresh the page"
    },
    "otherTitle": "To enable camera access:",
    "safariSteps": {
      "0": "Open the page settings (\"aA\" in the address bar) or Safari settings",
      "1": "Go to Websites > Camera",
      "2": "Find this website and select \"Allow\"",
      "3": "Refresh the page"
    },
    "safariTitle": "To enable camera access in Safari:",
    "unavailable": "The camera only works over a secure connection. Open the app with https:// and try again.",
    "waiting": "Waiting for camera access…"
  },
  "common": {
    "dismiss": "Dismiss",
    "goToStart": "Go to start",
    "loading": "Loading",
    "loadingBook": "Loading book",
    "markAlt": "Mark the Page"
  },
  "entries": {
    "categories": {
      "glossary": "Glossary",
      "link": "Links",
      "text": "Texts",
      "video": "Videos"
    },
    "countAria": "{{consulted}} of {{total}} consulted",
    "empty": "No entries consulted yet.",
    "locked": "locked"
  },
  "entry": {
    "accessPage": "Access page",
    "author": "Author",
    "category": "Category",
    "entryName": "Entry name",
    "goToPage": "Go to access page {{page}} in scan mode to see the video.",
    "missing": "This entry is not part of the book (anymore).",
    "openInNewTab": "Open in a new tab",
    "preview": "Preview (the AR version is shown on the page):"
  },
  "header": {
    "backToScan": "Back to scan mode",
    "counterAria": "{{consulted}} of {{total}} entries consulted",
    "entries": "Entries",
    "entriesConsulted": "Entries consulted",
    "info": "Info",
    "openConsultation": "Open consultation mode"
  },
  "notFound": {
    "text": "This page doesn't exist (anymore)."
  },
  "progress": {
    "converted": "Your saved progress was converted for this app version. Parts of it may be missing.",
    "reset": "Your saved progress could not be read by this app version and was reset."
  },
  "scan": {
    "newEntryUnlocked": "New entry unlocked",
    "openEntry": "Open entry {{title}}",
    "pagesActivated": "Pages activated:",
    "pagesAria": "Pages {{pages}}"
  },
  "settings": {
    "feedbackDescription": "Short sounds and vibrations when you scroll through the pages, tap a button or find a page.",
    "hapticsLabel": "Vibration",
    "historyButton": "Reset book",
    "historyConfirm": "Delete all saved progress for this book on this device?",
    "historyDescription": "This will delete all saved progress on this device.",
    "historyDone": "All saved progress on this device was deleted.",
    "languageChange": "Change language",
    "languageLabel": "Language:",
    "off": "off",
    "on": "on",
    "soundLabel": "Sounds",
    "tutorialButton": "Tutorial",
    "tutorialDescription": "A step by step guide on how to use the app with your book."
  },
  "startup": {
    "contentNotLoaded": "The book content could not be loaded.",
    "contentOtherVersion": "The book content was built for another app version.",
    "unknownError": "An unknown error occurred."
  },
  "tutorial": {
    "skip": "Skip"
  }
}
